query Matrices($lang: String) {
    matrices(lang: $lang) {
        rarity
        name
        id
        assets {
            iconLarge
        }
        banners {
            bannerNumber
        }
        __typename
    }
}