query MyQuery {
    simulacrav2 {
        name
        id
        weapon {
            element
            rarity
            type
            charge {
                tier
                value
            }
            shatter {
                tier
                value
            }
        }
        banners {
            bannerNo
        }
        assets {
            avatar
            artwork
            painting
        }
        __typename
    }
    matrices {
        rarity
        name
        assets {
            iconLarge
        }
        __typename
    }
}