query MyQuery {
  simulacrav2 {
    name
    id
    weapon {
      element
      rarity
      type
    }
    assets {
      avatar
      artwork
      painting
    }
  }
  matrices {
    
    rarity
    name
  }
}