query MyQuery {
    simulacrav2 {
        name
        id
        weapon {
            element
            rarity
            type
        }
        assets {
            avatar
            artwork
            painting
        }
        __typename
    }
    matrices {
        rarity
        name
        assets {
            icon
        }
        __typename
    }
}