query Weapon($lang: String, $id: String) {
    weapon(lang: $lang, id: $id) {
        rarity
        name
        id
        simulacrumId
        assets {
            icon
        }
        element
        category
        charge {
            tier
            value
        }
        shatter {
            tier
            value
        }
        banners {
            bannerNumber
            isFinalBanner
            detailsLink
            endDate
            isCollab
            isLimitedBannerOnly
            isRerun
            matrixId
            simulacrumId
            simulacrumName
            startDate
            weaponId
        }
        weaponEffects {
            description
            title
        }
        elementEffect {
            description
            title
        }
        weaponAdvancements {
            charge {
                tier
                value
            }
            shatter {
                tier
                value
            }
            description
            need
        }
        weaponAttacks {
            normals {
                description
                icon
                name
                operations
                tags
                values
            }
            skill {
                description
                icon
                name
                operations
                tags
                values
            }
            dodge {
                description
                icon
                name
                operations
                tags
                values
            }
            discharge {
                description
                icon
                name
                operations
                tags
                values
            }
        }
        weaponStats {
            icon
            name
        }
        meta {
            analyticVideoId
            rating
            recommendedMatrices {
                id
                pieces
            }
            recommendedPairings
        }
        __typename
    }
}