query Weapon($lang: String, $id: String) {
    weapon(lang: $lang, id: $id) {
        rarity
        name
        id
        simulacrumId
        assets {
            icon
        }
        element
        category
        charge {
            tier
            value
        }
        shatter {
            tier
            value
        }
        banners {
            bannerNumber
        }
        weaponEffects {
            description
            title
        }
        weaponAdvancements {
            charge {
                tier
                value
            }
            shatter {
                tier
                value
            }
            description
            need
        }
        weaponAttacks {
            normals {
                description
                icon
                name
                operations
                tags
                values
            }
            skill {
                description
                icon
                name
                operations
                tags
                values
            }
            dodge {
                description
                icon
                name
                operations
                tags
                values
            }
            discharge {
                description
                icon
                name
                operations
                tags
                values
            }
        }
        __typename
    }
}