fragment foodEntry on FoodType {
    # Include everything
    id
    buff
    categories
    description
    effect
    icon
    name
    rarity
    stars
    ingredients {
        matID {
            description
            icon
            id
            name
            type
            rarity
        }
        max
        min
        source
    }
}