fragment matrixEntry on Matrice {
    id
    rarity
    name
    version
    assets {
        iconLarge
    }
    banners {
        bannerNumber
        isFinalBanner
        endDate
        startDate
    }
}