fragment simulacrum_v2Entry on SimulacraV2 {
    name
    rarity
    id
    weaponId
    matrixId
    version
    banners {
        bannerNumber
        isFinalBanner
    }
    assetsA0 {
        painting
        avatar
        titlePicture
    }
    weapon {
        rarity
        element
        category
        charge {
            tier
            value
        }
        shatter {
            tier
            value
        }
    }
}