fragment simulacrumEntry on Simulacra {
    name
    rarity
    id
    weaponId
    matrixId
    version
    banners {
        bannerNumber
        isFinalBanner
        endDate
    }
    assetsA0 {
        painting
        avatar
        titlePicture
    }
}