fragment weaponEntry on Weapon {
    rarity
    name
    id
    version
    assets {
        icon
    }
    element
    category
    charge {
        tier
        value
    }
    shatter {
        tier
        value
    }
    banners {
        bannerNumber
        isFinalBanner
        endDate
        startDate
    }
}