query AllWeapons {
    weapons {
        rarity
        name
        assets {
            icon
        }
        element
        type
        charge {
            tier
            value
        }
        shatter {
            tier
            value
        }
        banners {
            bannerNo
        }
        __typename
    }
}