query Entries($lang: String) {
    simulacra_v2(lang: $lang) {
        Name
        Rarity
        id
        Weapon {
            Rarity
            WeaponElement
            WeaponCategory
            Charge {
                tier
                value
            }
            Shatter {
                tier
                value
            }
        }
        Banners {
            bannerNo
        }
        AssetsA0 {
            AwakenPhoto
            Painting
        }
        __typename
    }
    weapons(lang: $lang) {
        Rarity
        Name
        Assets {
            ItemIcon
        }
        WeaponElement
        WeaponCategory
        Charge {
            tier
            value
        }
        Shatter {
            tier
            value
        }
        Banners {
            bannerNo
        }
        __typename
    }
    matrices(lang: $lang) {
        rarity
        name
        assets {
            iconLarge
        }
        Banners {
            bannerNo
        }
        __typename
    }
}