query AllEntries($lang: String) {
    simulacra_v2(lang: $lang) {
        name
        rarity
        id
        weapon {
            element
            rarity
            type
            charge {
                tier
                value
            }
            shatter {
                tier
                value
            }
        }
        banners {
            bannerNo
        }
        assets {
            avatar
            artwork
            painting
        }
        __typename
    }
    weapons(lang: $lang) {
        rarity
        name
        assets {
            icon
        }
        element
        type
        charge {
            tier
            value
        }
        shatter {
            tier
            value
        }
        banners {
            bannerNo
        }
        __typename
    }
    matrices(lang: $lang) {
        rarity
        name
        assets {
            iconLarge
        }
        banners {
            bannerNo
        }
        __typename
    }
}