query Simulacra($lang: String) {
    simulacra_v2(lang: $lang) {
        Name
        Rarity
        id
        Weapon {
            Rarity
            WeaponElement
            WeaponCategory
            Charge {
                tier
                value
            }
            Shatter {
                tier
                value
            }
        }
        Banners {
            bannerNo
        }
        AssetsA0 {
            Avatar
            AwakenPhoto
            Painting
        }
        __typename
    }
}