query AllBanners($version: String) {
    banners(version: $version) {
        bannerNumber
        category
        detailsLink
        element
        endDate
        isFinalBanner
        isCollab
        isLimitedBannerOnly
        isRerun
        matrixId
        noWeapon
        simulacrumId
        simulacrumName
        startDate
        weaponId
    }
}