query FullServant($id: String!) {
    servant(id: $id) {
        ...servantEntry
        advancements {
            description
            mats {
                amount
                description
                icon
                id
                name
                rarity
                type
            }
        }
        description
        skills {
            description
            icon
            name
        }
        upgradeItems {
            exp
            material {
                description
                icon
                id
                name
                rarity
                type
            }
        }
        properties
    }
}