query FullMatrix($id: String!, $lang: String, $version: String) {
    matrix(id: $id, lang: $lang, version: $version) {
        ...matrixEntry
        description
        meta {
            recommendedWeapons
            # lastUpdated {
            #     username
            #     timestamp
            # }
        }
        sets {
            description
            need
        }
        simulacrumId
    }
}