query FullServant($id: String!, $lang: String, $version: String) {
    servant(id: $id, lang: $lang, version: $version) {
        ...servantEntry
        advancements {
            description
            mats {
                amount
                description
                icon
                id
                name
                rarity
                type
            }
        }
        description
        skills {
            description
            icon
            name
        }
        upgradeItems {
            exp
            material {
                description
                icon
                id
                name
                rarity
                type
            }
        }
        properties
    }
}