query FullMount($id: String!, $lang: String, $version: String) {
    mount(id: $id, lang: $lang, version: $version) {
        ...mountEntry
        description
        rarity
        unlockItems {
            amount
            item {
                description
                icon
                id
                name
                rarity
                type
            }
        }
        version
    }
}