query FullSimulacrumV2($id: String!) {
    simulacrumV2(id: $id) {
        ...simulacrum_v2Entry
        advanceId
        affiliation
        avatarId
        awakening {
            description
            icon
            name
            need
        }
        assetsA0 {
            descPainting
        }
        birthday
        gender
        guidebook {
            description
            icon
            title
        }
        height
        homeTown
        likedGiftTypes
        dislikedGiftTypes
        voicing {
            cn
            en
            jp
            kr
            pt
        }
    }
}