query FullEquipment($id: String!) {
    gear(id: $id) {
        ...equipmentEntry
        baseStat {
            propName
            propValue
        }
        source
        statPool {
            propName
            weightValue
        }
    }
}