query FullSimulacrumV2($id: String) {
    simulacrum_v2(id: $id) {
        ...simulacrum_v2Entry
        advanceId
        affiliation
        avatarId
        awakening {
            description
            icon
            name
            need
        }
        birthday
        gender
        height
        homeTown
        id
        isReleased
        likedGiftTypes
        matrixId
        name
        rarity
        version
        voicing {
            cn
            en
            jp
            kr
            pt
        }
        weaponId
    }
}