query FullEquipment($id: String!) {
    gear(id: $id) {
        ...equipmentEntry
        maxLevel
        advancement {
            amount
            icon
            matId
            name
            rarity
        }
        baseStat {
            propName
            propValue
            icon
            name
        }
        statPool {
            propName
            weightValue
            icon
            name
        }
        props {
            PropId
            PropInitValue
            PropMaxValue
            PropMinValue
            Quality
        }
    }
}