query FullWeapon($id: String) {
    weapon(id: $id) {
        ...weaponEntry
        simulacrumId
        weaponEffects {
            description
            title
        }
        elementEffect {
            description
            title
        }
        upgradeMats {
            items {
                matId
                amount
                icon
                name
                rarity
            }
        }
        weaponAdvancements {
            charge {
                tier
                value
            }
            shatter {
                tier
                value
            }
            description
            need
            multiplier {
                coefficient
                statId
            }
        }
        weaponAttacks {
            normals {
                description
                icon
                name
                operations
                tags
                values
            }
            skill {
                description
                icon
                name
                operations
                tags
                values
            }
            dodge {
                description
                icon
                name
                operations
                tags
                values
            }
            discharge {
                description
                icon
                name
                operations
                tags
                values
            }
        }
        weaponStats {
            id
            name
            icon
            value
            upgradeProp
        }
        meta {
            analyticVideoId
            rating
            recommendedMatrices {
                id
                pieces
            }
            recommendedPairings
            lastUpdated {
                username
                # timestamp
            }
        }
    }
}