query FullMount($id: String!) {
    mount(id: $id) {
        ...mountEntry
        description
        rarity
        unlockItems {
            amount
            item {
                description
                icon
                id
                name
                rarity
                type
            }
        }
        version
    }
}