query FullEquipment($id: String!, $lang: String, $version: String) {
    gear(id: $id, lang: $lang, version: $version) {
        ...equipmentEntry
        maxLevel
        advancement {
            amount
            icon
            matId
            name
            rarity
        }
        advancementExp
        baseStat {
            propName
            propValue
            icon
            name
        }
        baseUpgradeProps {
            multiplier
            propId
        }
        expValue
        matList
        statPool {
            propName
            weightValue
            icon
            name
        }
        props {
            PropId
            PropInitValue
            PropMaxValue
            PropMinValue
            Quality
        }
        gearUpgradeProps
    }
}