query FullRelic($id: String!, $lang: String, $version: String) {
    relic(id: $id, lang: $lang, version: $version) {
        ...relicEntry
        advancements
        description
        source
    }
}